name: dev_test
version: 1.0.0+3
description: Test utilities for dart and flutter packages.
repository: https://github.com/tekartik/dev_test.dart/tree/master/dev_test

environment:
  sdk: ^3.5.0

dependencies:
  test_core: '>=0.3.0 <2.0.0'
  test_api: '>=0.2.1 <2.0.0'
  matcher: '>=0.12.16 <2.0.0'
  dev_build: '>=1.0.0 <3.0.0'
  process_run: '>=1.0.0-0 <3.0.0'
  pub_semver: '>=2.1.4 <4.0.0'
  yaml: '>=3.1.2 <5.0.0'
  path: '>=1.8.3 <3.0.0'
  meta: '>=1.9.0 <3.0.0'
  pool: '>=1.5.1 <3.0.0'
  args: '>=2.4.2 <4.0.0'
  synchronized: '>=3.0.0+3 <5.0.0'
dev_dependencies:
  test: '>=1.24.0 <3.0.0'
  build_runner: '>=2.4.6'
  build_test: '>=2.2.0'
  build_web_compilers: '>=4.0.5'
  lints: '>=2.1.1'

